### ISSUE TITLE
No Issue - Just a Request

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/MB-220-Dynamics365forMarketing#28]
Hello 

I have been asked to deliver the MB-220. I reviewed the Closed issues and see they go back to 2021. I know that the Dataverse continues to be updated as do many portals that access it. There are no Active issues outstanding which is rare. 

I am curious to know if the Author or any of the contributors have delivered the course in the last month and what was their experience. 

Thank you. 

# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by anjenni** [comment]
Hi Arnold! I'm not an MCT, I'm just the content developer who manages this repo, but this might help inform your question. We now employ a lab testing service that performs periodic testing of the labs end-to-end. They use Pull Requests to log the bugs so we can easily merge the fixes. As a result, I've seen fewer Issues being raised - I think the lab testing service is just catching bugs first, which is great. 

I'm leaving your issue open so other MCTs can weigh in and I'll be following the thread to see if there's anything raised that I can fix. Thanks Arnold.

**Comment by arnoldvilleneuve** [comment]
Thank you for the follow up. 
From what I can see that last update to the labs were 4 months ago. I hope to hear from an MCT that has delivered the content and the labs recently. 
Question: If the testing service finds an issue will it show up in Github? 
Thank you again. 
Arnold Villeneuve 613-833-0984 

    On Monday, August 8, 2022 at 06:39:45 p.m. EDT, Anna Jennings ***@***.***> wrote:  
 
 


Hi Arnold! I'm not an MCT, I'm just the content developer who manages this repo, but this might help inform your question. We now employ a lab testing service that performs periodic testing of the labs end-to-end. They use Pull Requests to log the bugs so we can easily merge the fixes. As a result, I've seen fewer Issues being raised - I think the lab testing service is just catching bugs first, which is great.

I'm leaving your issue open so other MCTs can weigh in and I'll be following the thread to see if there's anything raised that I can fix. Thanks Arnold.

**Comment by anjenni** [comment]
Yes, they show up under the closed Pull Requests. You'll see the most recent pull request was in April 2022, but the most recent end-to-end testing was actually in July, so just 1 month ago. They didn't find any changes needed in July so no pull request was made. Hopefully that helps! :)

**Comment by arnoldvilleneuve** [comment]
It is ALL helpful. Thank you. 
The news about Microsoft engaging full ongoing end-to-end testing of labs is FANTASTIC. It will help us focus on the event content and lab experience as opposed to troubleshooting. I have seen talk of this in the MCT Central but it is great to see it in action. It is indeed welcome news. 
Arnold Villeneuve 613-833-0984 

    On Monday, August 8, 2022 at 06:55:40 p.m. EDT, Anna Jennings ***@***.***> wrote:  
 
 


Yes, they show up under the closed Pull Requests. You'll see the most recent pull request was in April 2022, but the most recent end-to-end testing was actually in July, so just 1 month ago. They didn't find any changes needed in July so no pull request was made. Hopefully that helps! :)

**Comment by anjenni** [comment]
So great to hear. It was definitely welcome news for us too! ;) Hopefully everything goes smoothly with your class and don't hesitate to follow up with any issues you find.

**Comment by anjenni** [comment]
Hi Arnold - I'm going to close this issue out so it's not outstanding, but please feel free to open another if you still have questions (or email me directly). Thank you!

**Comment by julians1966** [comment]
Arnold, I have just seen your question. I delivered this back in June/July.
This is one of my favourite courses to deliver, more because I tend to get marketing professionals rather than IT people attending so the conversations are more fruitful. 
The Marketing app is unlike the rest of the Dynamics 365 apps in that you don't really customize it, however there is a lot of configuration required and the course works through this. An issue with the course/app is that the students don't really see anything until all the configuration has been completed e.g, customer journeys and an email until late in the course. I create an end-end demo which I should for the beginning of the course so help students understand and out into context what they will be doing, This initial demo is very important for me.
I also have created a web app in Azure that I can deploy my landing pages to, and I also have created a web app with its own form so that I can demo form capture.
